MachineIntelligenceCore:Toolchain: mic::configuration::PropertyInterface Class Reference
mic::configuration::PropertyInterface Class Reference abstract
Basic interface property - used during registration etc.
#include <Property.hpp>
Public Member Functions
PropertyInterface (const std::string &name_)
virtual ~PropertyInterface ()
const std::string & name () const
virtual void setValue (const std::string &str)=0
virtual std::string getValue ()=0
Private Attributes
std::string property_name
Name of the property.
Detailed Description
Basic interface property - used during registration etc.
Author
tkornuta
Definition at line 90 of file Property.hpp.
Constructor & Destructor Documentation
mic::configuration::PropertyInterface::PropertyInterface (const std::string & name_) inline
Definition at line 93 of file Property.hpp.
virtual mic::configuration::PropertyInterface::~PropertyInterface () inline virtual
Definition at line 97 of file Property.hpp.
Member Function Documentation
virtual std::string mic::configuration::PropertyInterface::getValue () pure virtual
Abstract method for returning the string representing the current value.
Returns
string representation of current value.
Implemented in mic::configuration::Property< T, Translator >, mic::configuration::Property< long >, mic::configuration::Property< unsigned long >, mic::configuration::Property< double >, mic::configuration::Property< unsigned int >, and mic::configuration::Property< bool >.
Referenced by mic::configuration::PropertyTree::loadPropertiesFromConfigNode().
const std::string& mic::configuration::PropertyInterface::name () const inline
Returns property name.
Returns
Name.
Definition at line 103 of file Property.hpp.
References property_name.
Referenced by mic::configuration::PropertyTree::loadPropertiesFromConfigNode(), and mic::configuration::PropertyTree::registerProperty().
virtual void mic::configuration::PropertyInterface::setValue (const std::string & str) pure virtual
Abstract method for retrieving the value of property from a string, defined in concrete property.
Parameters
str String from which value will be retrieved.
Implemented in mic::configuration::Property< T, Translator >, mic::configuration::Property< long >, mic::configuration::Property< unsigned long >, mic::configuration::Property< double >, mic::configuration::Property< unsigned int >, and mic::configuration::Property< bool >.
Referenced by mic::configuration::PropertyTree::loadPropertiesFromConfigNode().
Member Data Documentation
std::string mic::configuration::PropertyInterface::property_name private
Name of the property.
Definition at line 122 of file Property.hpp.
Referenced by name().
The documentation for this class was generated from the following file:
src/configuration/Property.hpp