MachineIntelligenceCore:Toolchain: mic::logger::ConsoleOutput Class Reference
mic::logger::ConsoleOutput Class Reference
Class responsible for printing logs on console.
#include <ConsoleOutput.hpp>
Public Member Functions
ConsoleOutput (Severity_t sev=LINFO)
virtual ~ConsoleOutput ()
void print (const std::string &msg, Severity_t sev, const std::string &file, int line) const
Public Member Functions inherited from mic::logger::LoggerOutput
LoggerOutput (Severity_t sev=LINFO)
virtual ~LoggerOutput ()
void setLvl (Severity_t sev)
void incrementLvl ()
void decrementLvl ()
Severity_t getLvl () const
Additional Inherited Members
Protected Attributes inherited from mic::logger::LoggerOutput
Severity_t lvl
Detailed Description
Class responsible for printing logs on console.
Definition at line 185 of file ConsoleOutput.hpp.
Constructor & Destructor Documentation
mic::logger::ConsoleOutput::ConsoleOutput (Severity_t sev = LINFO) inline
Constructor. Sets default severity level (LINFO as default).
Parameters
sev Default output severity level.
Definition at line 191 of file ConsoleOutput.hpp.
virtual mic::logger::ConsoleOutput::~ConsoleOutput () inline virtual
Virtual destructor. Empty.
Definition at line 200 of file ConsoleOutput.hpp.
Member Function Documentation
void mic::logger::ConsoleOutput::print (const std::string & msg, Severity_t sev, const std::string & file, int line) const inline virtual
Prints message on console, with colours.
Parameters
msg Message to be printed.
sev Severity level.
file File that called the log function.
line Line in which log function was called.
Implements mic::logger::LoggerOutput.
Definition at line 210 of file ConsoleOutput.hpp.
References mic::logger::cyan(), mic::logger::Debug, mic::logger::Error, mic::logger::Fatal, mic::logger::green(), mic::logger::Info, mic::logger::intense(), mic::logger::Notice, mic::logger::red(), mic::logger::reset(), mic::logger::sev2str(), mic::logger::Status, mic::logger::Trace, mic::logger::Warning, and mic::logger::yellow().
The documentation for this class was generated from the following file:
src/logger/ConsoleOutput.hpp